# Generated by Django 5.2.16 on 2026-07-19 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fresher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('technology', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('joining_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=200)),
                ('hours', models.IntegerField()),
                ('tasks', models.TextField()),
                ('challenges', models.TextField(blank=True)),
                ('fresher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.fresher')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=200)),
                ('github_link', models.URLField(blank=True)),
                ('status', models.CharField(max_length=30)),
                ('fresher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.fresher')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('technology', models.CharField(max_length=100)),
                ('progress', models.IntegerField()),
                ('github_link', models.URLField(blank=True)),
                ('fresher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.fresher')),
            ],
        ),
    ]
